apiVersion: v1
kind: BuildConfig
metadata:
  labels:
    app: python-nginx-pipeline
  name: python-nginx-pipeline
spec:
  source:
    git:
      ref: master
      uri: <your git repository link>
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: path/to/Jenkinsfile
    type: JenkinsPipeline
  triggers:
    - github:
        secret: secret
      type: GitHub
    - generic:
        secret: secret
      type: Generic
    - bitbucket:
        secret: secret
      type: Bitbucket